### PR TITLE
Adding in drawings for gaskets and assemblies

### PR DESCRIPTION
**Pull request by darraghbr**
Addresses #63 #29 #25 and adds drawings for the gaskets.

### CODE REVIEW

**Review by mechatroniks-git — COMMENTED** [review]
Be sure to add centerlines on all arcs & circles, if they are using a compass/circular gasket cutter, will make it easier. 

image


Also, recommend picking one datum and dimensioning from there

image

Arrow here is obstructing outline 
image

**Comment by darraghbr** [comment]
I've addressed your comments I hope, I did try to do what you suggested in your second comment but it looks too cramped and hard to read, so I've left it the way it is, but I did add in hole center marking on that one, as well as the first drawing you commented on.

**Comment by mechatroniks-git** [comment]
https://github.com/darraghbr/papr-print-files/blob/main/Gaskets/Drawings/D-TET-000125-0%20Mask%20Gasket%20drawing%20A.pdf can use it as well.
image

**Comment by mechatroniks-git** [comment]
@darraghbr - could you add centerlines to this: https://github.com/darraghbr/papr-print-files/blob/main/Gaskets/Drawings/D-TET-000125-0%20Mask%20Gasket%20drawing%20A.pdf

**Comment by darraghbr** [comment]
> 
> 
> @darraghbr - could you add centerlines to this: 

I feel it is unnecessary given the concentricity markings but ok.

[D-TET-000125-0 Mask Gasket drawing A.pdf](https://github.com/tetrabiodistributed/papr-print-files/files/6068428/D-TET-000125-0.Mask.Gasket.drawing.A.pdf)

**Comment by mechatroniks-git** [comment]
It might be unnecessary, but useful if someone is cutting gaskets by hand, using one of these: https://www.mcmaster.com/gasket-cutters/circular-gasket-cutters-7/

Thanks Darragh

**Review by mechatroniks-git — APPROVED** [review]

**Pull request merged**
