### PR TITLE
WIP: updating all STEP and STL files for stealth 96mm sanyo with part numbers

### PR DESCRIPTION
**Pull request by mmroden**
Got the STLs and STEP files in there, we need new assembly drawings

### CODE REVIEW

**Comment by Burhan-Q** [comment]
Waiting on F360 license

- [ ] Exploded diagram needed :: PAPR 96mm Fan Secure (Stealth Filter Sanyo)
- [ ] Exploded diagram needed :: PAPR 96mm Fan Battery Holder (same location as above)

> [!NOTE]
> Not all hardware is included in assemblies and may need to be added for exploded diagrams

> [!IMPORTANT] 
> See Slack post for Gasket SVGs from @DHHwangPhD

**Comment by mmroden** [comment]
Added in the 96mm gaskets, so that's there.

**Comment by Burhan-Q** [comment]
@mmroden exploded assembly drawings added as PDFs

**Comment by mmroden** [comment]
@Burhan-Q is it possible to add the part numbers into the assembly diagrams?  I got them on all the parts, but I understand that it could be a PITA

**Comment by Burhan-Q** [comment]
It will be a bit of a pain, but I'll see if I can squeeze in some time. I did this in the past, but I think it could've been a forked model that required changing for the drawings. Hopefully these models can get used for a while so the part numbers don't need to get added each time.

**Comment by Burhan-Q** [comment]
Just going to drop a note that I doubt it will happen tomorrow, but if by this time Wednesday 2024-04-03 there's no updates, then I ran short on time to get back to adding these.

**Review by capsulecorplab — APPROVED** [review]
Controller board STL's LGTM

**Review by capsulecorplab — APPROVED** [review]
96mm & 120mm fan boxes LGTM

**Pull request merged**
