### PR TITLE
PCB assembly jig

### PR DESCRIPTION
**Pull request by MarkPorter66**
The files for the current pcb assembly jig

### CODE REVIEW

**Review by capsulecorplab — CHANGES_REQUESTED** [review]
STEP and STL files should be oriented, such that base is on the bottom, for ease of slicing

**Comment by MarkPorter66** [comment]
Removed reduntant file and reorientated the current STL

**Review by capsulecorplab — CHANGES_REQUESTED** [review]
jig_low_support_marked
One of the jig supports is a bit low

**Review by capsulecorplab — COMMENTED** [review]
Just printed the changes as of https://github.com/tetrabiodistributed/papr-print-files/pull/236/commits/7b912a71133c1c79e1353aabc13bd14339cf33cd

The new LED height looks good!
PXL_20231118_192651368
PXL_20231118_192635435

Though, I noticed a bit of clearance between the battery leads and block underneath it. Should we increase the height of that block? It's about a 1.5mm gap
PXL_20231118_192647571
PXL_20231118_193611570 MP

**Comment by mmroden** [comment]
Closing for #239

**Pull request closed without merging**
