### PR TITLE
10/4 Upload

### PR DESCRIPTION
**Pull request by DHHwangPhD**
Uploaded Latest alpha stl and svg for PAPRa

### CODE REVIEW

**Review by darraghbr — CHANGES_REQUESTED** [review]
I see we have P-TET-000133-2 and P-TET-000133-2S. We should probably have these as seperate part numbers?

**Comment by mmroden** [comment]
Will close #160, #162, #168

**Review by mmroden — CHANGES_REQUESTED** [review]
I'm seeing duplicates of some of the parts (ie, 7 and 8 of the fan box, with 8 not in the right print orientation, 8 and 9 of the filter housing, 3 and 4 of the weather guard) where I'd expect only one part, and also we're missing the dxfs of the gaskets.

**Comment by mmroden** [comment]
lgtm

**Pull request merged**
